# Generated by Django 4.0.5 on 2022-06-22 19:54

from django.db import migrations, models
import share.validators


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='', validators=[share.validators.file_size], verbose_name='video')),
            ],
        ),
    ]
