# Generated by Django 4.0.5 on 2022-06-22 20:45

import cloudinary.models
from django.db import migrations
import share.validators


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[share.validators.file_size], verbose_name='video'),
        ),
    ]
