# Generated by Django 4.0.5 on 2022-06-22 21:28

import cloudinary.models
import cloudinary_storage.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[cloudinary_storage.validators.validate_video], verbose_name='video'),
        ),
    ]
